PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX plwn: <http://plwordnet.pwr.wroc.pl/wordnet/synset/>

SELECT ?c ?c2 ?c3
{
  BIND (plwn:82272 as ?c)
  ?c skos:broader ?c2 .
}
